[package]
name = "jarbas"
version = "2.0.0"
edition = "2021"

[dependencies]
spin = "0.9"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
x86_64 = "0.14.11"
libm = "0.2"
event-bus = { path = "../event-bus" }
ticket-lock = { path = "../ticket-lock" }
agent-core = { path = "../agent-core" }
skill-registry = { path = "../skill-registry" }
k-nano = { path = "../k_nano" }
cortex = { path = "../cortex" }
hermes = { path = "../hermes" }
bootloader_api = "0.11.15"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(feature, values("kernel"))'] }
