//! Cognitive Adaptation Engine
//! 
//! Hermes (Meta-Cognitive Supervisor) receives hardware topology reports from k-nano
//! and automatically decides execution policies for the operating system.
//! 
//! # Adaptation Cycle
//! 1. Receive XeonTopologyReport from k-nano during boot
//! 2. Classify hardware generation (Old vs Modern Xeon)
//! 3. Generate ExecutionStrategy based on hardware capabilities
//! 4. Apply policies: socket isolation, core pinning, SIMD dispatch, MoE sizing

#![allow(dead_code)]
#![allow(unused_unsafe)]

use core::sync::atomic::{AtomicBool, Ordering};

pub mod client;
pub mod epyc;

/// Re-export Xeon topology types from k-nano
pub use k_nano::hardware::xeon::{
    XeonTopologyReport, XeonGeneration, InterconnectType,
    l3_cache_per_socket, optimal_moe_expert_size,
    has_avx512, has_amx, is_old_xeon, is_modern_xeon, recommended_simd_width,
};

/// Execution Strategy determined by Hermes based on hardware
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum ExecutionStrategy {
    /// Unknown or unsupported hardware
    Unknown = 0,
    
    /// Old Xeon Strategy (E5 v3/v4 - AVX2, QPI, DDR4)
    /// - Socket isolation: Socket 0 for hermes/jarbas/VFS, Socket 1 for cortex/k-ai
    /// - Limited inter-socket traffic via async MPMC messages
    /// - MoE sized to fit in L3 cache (~35MB per expert for 45MB L3)
    /// - AVX2 SIMD dispatch (256-bit, 128 weights/cycle)
    OldXeon = 1,
    
    /// Modern Xeon Strategy (Sapphire/Emerald/Granite - AVX-512, AMX, DDR5)
    /// - Massive cellular distribution across all cores
    /// - Core pinning with dedicated threads (Cognitive Cells A.2)
    /// - AVX-512/AMX dispatch (512-bit, 256 weights/cycle)
    /// - High-bandwidth UPI interconnect
    ModernXeon = 2,
    
    /// Fallback strategy for unsupported hardware
    Fallback = 3,
}

impl ExecutionStrategy {
    pub fn name(self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::OldXeon => "Old Xeon (E5 v3/v4)",
            Self::ModernXeon => "Modern Xeon (AVX-512/AMX)",
            Self::Fallback => "Fallback",
        }
    }
}

/// Socket isolation policy for NUMA systems
#[derive(Debug, Clone, Copy, Default)]
#[repr(C)]
pub struct SocketIsolationPolicy {
    /// Socket ID for hermes, jarbas, and VFS (Memory L0-L7)
    pub hermes_socket: u8,
    /// Socket ID for cortex and k-ai
    pub cortex_socket: u8,
    /// Enable strict isolation (no cross-socket traffic except async messages)
    pub strict_isolation: bool,
    /// Maximum inter-socket message rate (messages/sec)
    pub max_inter_socket_rate: u32,
}

/// Core pinning policy for thread-to-core assignment
#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct CorePinningPolicy {
    /// Enable core pinning (thread affinity)
    pub enable_pinning: bool,
    /// Use spin-loop instead of preemption for critical threads
    pub spin_loop_critical: bool,
    /// Number of cognitive cells (worker threads) to spawn
    pub cognitive_cell_count: u16,
    /// Core IDs for hermes threads
    pub hermes_cores: [u8; 8],
    /// Core IDs for cortex threads
    pub cortex_cores: [u8; 64],
}

impl Default for CorePinningPolicy {
    fn default() -> Self {
        Self {
            enable_pinning: false,
            spin_loop_critical: false,
            cognitive_cell_count: 0,
            hermes_cores: [0; 8],
            cortex_cores: [0; 64],
        }
    }
}

/// SIMD dispatch policy
#[derive(Debug, Clone, Copy, Default)]
#[repr(C)]
pub struct SimdDispatchPolicy {
    /// SIMD width in bits (128, 256, or 512)
    pub simd_width: u32,
    /// Use AVX-512 if available
    pub use_avx512: bool,
    /// Use AMX if available
    pub use_amx: bool,
    /// Use AVX2 if available
    pub use_avx2: bool,
    /// Weights processed per cycle (128 for AVX2, 256 for AVX-512)
    pub weights_per_cycle: u32,
}

/// MoE (Mixture of Experts) sizing policy
#[derive(Debug, Clone, Copy, Default)]
#[repr(C)]
pub struct MoESizingPolicy {
    /// Maximum expert size in bytes (must fit in L3)
    pub max_expert_size_bytes: usize,
    /// Number of experts per socket
    pub experts_per_socket: u8,
    /// Force in-cache execution (no spillover to RAM)
    pub force_in_cache: bool,
    /// L3 cache utilization percentage (0-100)
    pub l3_utilization_percent: u8,
}

/// Complete adaptation policy generated by Hermes
#[derive(Debug, Clone, Copy)]
#[repr(C)]
pub struct AdaptationPolicy {
    /// Execution strategy
    pub strategy: ExecutionStrategy,
    /// Socket isolation policy
    pub socket_isolation: SocketIsolationPolicy,
    /// Core pinning policy
    pub core_pinning: CorePinningPolicy,
    /// SIMD dispatch policy
    pub simd_dispatch: SimdDispatchPolicy,
    /// MoE sizing policy
    pub moe_sizing: MoESizingPolicy,
}

impl Default for AdaptationPolicy {
    fn default() -> Self {
        Self {
            strategy: ExecutionStrategy::Unknown,
            socket_isolation: SocketIsolationPolicy::default(),
            core_pinning: CorePinningPolicy::default(),
            simd_dispatch: SimdDispatchPolicy::default(),
            moe_sizing: MoESizingPolicy::default(),
        }
    }
}

/// Global adaptation policy (set once during boot)
static ADAPTATION_POLICY: core::sync::atomic::AtomicPtr<AdaptationPolicy> = 
    core::sync::atomic::AtomicPtr::new(core::ptr::null_mut());

/// Flag indicating if adaptation has been performed
static ADAPTED: AtomicBool = AtomicBool::new(false);

/// Generate execution strategy based on Xeon topology report
pub fn generate_strategy(report: &XeonTopologyReport) -> ExecutionStrategy {
    match report.generation {
        XeonGeneration::Old => ExecutionStrategy::OldXeon,
        XeonGeneration::Modern | XeonGeneration::Latest => ExecutionStrategy::ModernXeon,
        XeonGeneration::Unknown => {
            // Fallback based on available features
            if report.flags.avx2 {
                ExecutionStrategy::OldXeon
            } else if report.flags.sse42 {
                ExecutionStrategy::Fallback
            } else {
                ExecutionStrategy::Fallback
            }
        }
    }
}

/// Generate socket isolation policy for old Xeon systems
fn generate_old_xeon_socket_isolation(report: &XeonTopologyReport) -> SocketIsolationPolicy {
    if report.socket_count >= 2 {
        // Dual-socket: strict isolation
        SocketIsolationPolicy {
            hermes_socket: 0,
            cortex_socket: 1,
            strict_isolation: true,
            max_inter_socket_rate: 1000, // Limit QPI traffic
        }
    } else {
        // Single-socket: no isolation needed
        SocketIsolationPolicy {
            hermes_socket: 0,
            cortex_socket: 0,
            strict_isolation: false,
            max_inter_socket_rate: u32::MAX,
        }
    }
}

/// Generate socket isolation policy for modern Xeon systems
fn generate_modern_xeon_socket_isolation(report: &XeonTopologyReport) -> SocketIsolationPolicy {
    // Modern Xeon with UPI can handle more inter-socket traffic
    if report.socket_count >= 2 {
        SocketIsolationPolicy {
            hermes_socket: 0,
            cortex_socket: 1,
            strict_isolation: false, // UPI is faster than QPI
            max_inter_socket_rate: 10000, // Higher limit for UPI
        }
    } else {
        SocketIsolationPolicy {
            hermes_socket: 0,
            cortex_socket: 0,
            strict_isolation: false,
            max_inter_socket_rate: u32::MAX,
        }
    }
}

/// Generate core pinning policy for old Xeon systems
fn generate_old_xeon_core_pinning(report: &XeonTopologyReport) -> CorePinningPolicy {
    let total_cores = report.total_physical_cores;
    let hermes_cores_count = ((total_cores as u16) / 4).min(8) as u16;
    let cortex_cores_count = total_cores as u16 - hermes_cores_count;
    
    let mut hermes_cores = [0u8; 8];
    let mut cortex_cores = [0u8; 64];
    
    // Allocate first cores to hermes
    for i in 0..hermes_cores_count as usize {
        if i < 8 {
            hermes_cores[i] = i as u8;
        }
    }
    
    // Allocate remaining cores to cortex
    for i in 0..cortex_cores_count as usize {
        if i < 64 {
            cortex_cores[i] = (hermes_cores_count as u8 + i as u8).min(255);
        }
    }
    
    CorePinningPolicy {
        enable_pinning: true,
        spin_loop_critical: true, // Old Xeon benefits from spin-loop
        cognitive_cell_count: cortex_cores_count,
        hermes_cores,
        cortex_cores,
    }
}

/// Generate core pinning policy for modern Xeon systems
fn generate_modern_xeon_core_pinning(report: &XeonTopologyReport) -> CorePinningPolicy {
    let total_cores = report.total_physical_cores;
    let hermes_cores_count = ((total_cores as u16) / 8).min(8) as u16;
    let cortex_cores_count = total_cores as u16 - hermes_cores_count;
    
    let mut hermes_cores = [0u8; 8];
    let mut cortex_cores = [0u8; 64];
    
    // Allocate first cores to hermes
    for i in 0..hermes_cores_count as usize {
        if i < 8 {
            hermes_cores[i] = i as u8;
        }
    }
    
    // Allocate remaining cores to cortex (massive cellular distribution)
    for i in 0..cortex_cores_count as usize {
        if i < 64 {
            cortex_cores[i] = (hermes_cores_count as u8 + i as u8).min(255);
        }
    }
    
    CorePinningPolicy {
        enable_pinning: true,
        spin_loop_critical: false, // Modern Xeon has better scheduling
        cognitive_cell_count: cortex_cores_count,
        hermes_cores,
        cortex_cores,
    }
}

/// Generate SIMD dispatch policy
fn generate_simd_dispatch(report: &XeonTopologyReport) -> SimdDispatchPolicy {
    let simd_width = recommended_simd_width(report);
    let weights_per_cycle = if simd_width >= 512 { 256 } else if simd_width >= 256 { 128 } else { 64 };
    
    SimdDispatchPolicy {
        simd_width,
        use_avx512: report.flags.avx512f,
        use_amx: report.flags.amx,
        use_avx2: report.flags.avx2,
        weights_per_cycle,
    }
}

/// Generate MoE sizing policy for old Xeon systems
fn generate_old_xeon_moe_sizing(report: &XeonTopologyReport) -> MoESizingPolicy {
    let l3_size = l3_cache_per_socket(report) as usize;
    // Reserve 20% for other data, divide among 4 experts
    let max_expert_size = (l3_size * 80 / 100) / 4;
    
    MoESizingPolicy {
        max_expert_size_bytes: max_expert_size,
        experts_per_socket: 4,
        force_in_cache: true, // Force in-cache execution
        l3_utilization_percent: 80,
    }
}

/// Generate MoE sizing policy for modern Xeon systems
fn generate_modern_xeon_moe_sizing(report: &XeonTopologyReport) -> MoESizingPolicy {
    let l3_size = l3_cache_per_socket(report) as usize;
    // Modern Xeon has larger L3, can fit more experts
    let experts = (report.total_physical_cores as u8 / 4).max(4).min(16);
    let max_expert_size = (l3_size * 75 / 100) / (experts as usize);
    
    MoESizingPolicy {
        max_expert_size_bytes: max_expert_size,
        experts_per_socket: experts,
        force_in_cache: true,
        l3_utilization_percent: 75,
    }
}

/// Generate fallback policy for unsupported hardware
fn generate_fallback_policy() -> AdaptationPolicy {
    AdaptationPolicy {
        strategy: ExecutionStrategy::Fallback,
        socket_isolation: SocketIsolationPolicy {
            hermes_socket: 0,
            cortex_socket: 0,
            strict_isolation: false,
            max_inter_socket_rate: u32::MAX,
        },
        core_pinning: CorePinningPolicy {
            enable_pinning: false,
            spin_loop_critical: false,
            cognitive_cell_count: 1,
            hermes_cores: [0; 8],
            cortex_cores: [0; 64],
        },
        simd_dispatch: SimdDispatchPolicy {
            simd_width: 128,
            use_avx512: false,
            use_amx: false,
            use_avx2: false,
            weights_per_cycle: 64,
        },
        moe_sizing: MoESizingPolicy {
            max_expert_size_bytes: 1024 * 1024, // 1MB fallback
            experts_per_socket: 1,
            force_in_cache: false,
            l3_utilization_percent: 50,
        },
    }
}

/// Main adaptation function - generates complete policy from topology report
pub fn adapt_to_hardware(report: &XeonTopologyReport) -> AdaptationPolicy {
    let strategy = generate_strategy(report);
    
    let policy = match strategy {
        ExecutionStrategy::OldXeon => AdaptationPolicy {
            strategy,
            socket_isolation: generate_old_xeon_socket_isolation(report),
            core_pinning: generate_old_xeon_core_pinning(report),
            simd_dispatch: generate_simd_dispatch(report),
            moe_sizing: generate_old_xeon_moe_sizing(report),
        },
        ExecutionStrategy::ModernXeon => AdaptationPolicy {
            strategy,
            socket_isolation: generate_modern_xeon_socket_isolation(report),
            core_pinning: generate_modern_xeon_core_pinning(report),
            simd_dispatch: generate_simd_dispatch(report),
            moe_sizing: generate_modern_xeon_moe_sizing(report),
        },
        _ => generate_fallback_policy(),
    };
    
    policy
}

/// Set the global adaptation policy (call once during boot)
pub fn set_adaptation_policy(policy: AdaptationPolicy) {
    // In no_std, we'd use a static allocation. For now, this is a stub.
    let _ = policy;
    ADAPTED.store(true, Ordering::Release);
}

/// Get the current adaptation policy
pub fn get_adaptation_policy() -> Option<AdaptationPolicy> {
    if ADAPTED.load(Ordering::Acquire) {
        // In a real implementation, this would return the stored policy
        None // Stub for now
    } else {
        None
    }
}

/// Check if adaptation has been performed
pub fn is_adapted() -> bool {
    ADAPTED.load(Ordering::Acquire)
}

/// Get the current execution strategy
pub fn get_strategy() -> ExecutionStrategy {
    if let Some(policy) = get_adaptation_policy() {
        policy.strategy
    } else {
        ExecutionStrategy::Unknown
    }
}

/// Log the adaptation policy for debugging
pub fn log_adaptation_policy(policy: &AdaptationPolicy) {
    let _ = (policy,); // Suppress unused warning
    
    // In a real implementation, this would use the logging system
    // For now, we structure the data for the caller
}

/// Cognitive adaptation entry point - called by Hermes during boot
/// 
/// # Arguments
/// * `report` - Xeon topology report from k-nano
/// 
/// # Returns
/// The generated adaptation policy
pub fn cognitive_adaptation(report: &XeonTopologyReport) -> AdaptationPolicy {
    let policy = adapt_to_hardware(report);
    set_adaptation_policy(policy);
    log_adaptation_policy(&policy);
    policy
}






