//! InferenceFsAgent — arquivos gerados sob demanda.
//! Mount: /inference/

use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;
use core::sync::atomic::{AtomicU64, Ordering};
use spin::Mutex;
use crate::fs::FilesystemAgent;
use crate::serial_println;

static INFERENCE_COUNTER: AtomicU64 = AtomicU64::new(0);
static TRAINING_BUF: Mutex<Vec<(String, Vec<u8>)>> = Mutex::new(Vec::new());

fn get_tick() -> u64 {
    crate::interrupts::TIMER_TICKS.load(Ordering::Relaxed) as u64
}

fn generate_content(path: &str) -> Vec<u8> {
    let tick = get_tick();
    let training_count = TRAINING_BUF.lock().len();
    alloc::format!(
        "[InferenceFS] {} @ tick {}\nTraining examples: {}\nGenerated by Hermes Neural OS\n",
        path, tick, training_count
    ).into_bytes()
}

pub struct InferenceFsAgent;

impl InferenceFsAgent {
    pub fn new() -> Self {
        serial_println!("[INFERENCE-FS] /inference/ pronto.");
        InferenceFsAgent
    }
}

impl FilesystemAgent for InferenceFsAgent {
    fn name(&self) -> &str { "inference" }
    fn mount_point(&self) -> &str { "/inference" }

    fn read(&self, path: &str) -> Result<Vec<u8>, &str> {
        let key = path.trim_matches('/');
        if key.is_empty() { return Err("no path"); }
        INFERENCE_COUNTER.fetch_add(1, Ordering::Relaxed);
        Ok(generate_content(key))
    }

    fn write(&mut self, path: &str, data: &[u8]) -> Result<(), &str> {
        let key = String::from(path.trim_matches('/'));
        let mut buf = TRAINING_BUF.lock();
        if buf.len() >= 100 { buf.remove(0); }
        buf.push((key, data.to_vec()));
        serial_println!("[INFERENCE-FS] Training: {} ({} bytes)", path, data.len());
        Ok(())
    }

    fn list(&self, path: &str) -> Result<Vec<String>, &str> {
        match path.trim_matches('/') {
            "" => Ok(vec![
                String::from("weather"), String::from("network"),
                String::from("summary"), String::from("help"),
                String::from("training"),
            ]),
            _ => Ok(Vec::new()),
        }
    }
}
