[package]
name = "cortex"
version = "1.5.0"
edition = "2021"

[dependencies]
spin = "0.9"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
x86_64 = "0.14.11"
libm = "0.2"
event-bus = { path = "../event-bus" }
ticket-lock = { path = "../ticket-lock" }
k-nano = { path = "../k_nano" }
vector-db = { path = "../vector-db" }

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(feature, values("kernel"))'] }
